// Generated by CoffeeScript 1.6.3
var colors, normalize, spawn;

normalize = require('path').normalize;

spawn = require('child_process').spawn;

colors = require('colors');

module.exports.inspector = function(opts, kids, refresh) {
  var arg1, arg2, arg3, bin, debugPort, kid1, kid2, script, webPort, _ref;
  _ref = opts.args, arg1 = _ref[0], arg2 = _ref[1], arg3 = _ref[2];
  if (arg3 != null) {
    webPort = arg1;
    debugPort = arg2;
    script = arg3;
  } else if (arg2 != null) {
    webPort = arg1;
    debugPort = 5858;
    script = arg2;
  } else {
    webPort = 8080;
    debugPort = 5858;
    script = arg1;
  }
  bin = normalize(__dirname + '/../node_modules/.bin/node-inspector');
  kids.push(kid1 = spawn(bin, ["--web-port=" + (webPort || 8080)]));
  kid1.stderr.on('data', function(chunk) {
    return refresh(chunk.toString(), 'stderr');
  });
  kid1.stdout.on('data', function(chunk) {
    var str;
    str = chunk.toString();
    str = str.replace(/5858/, debugPort);
    return refresh(str);
  });
  bin = normalize(__dirname + '/../node_modules/.bin/node-dev');
  kids.push(kid2 = spawn(bin, ["--debug=" + debugPort, script]));
  kid2.stderr.on('data', function(chunk) {
    return refresh(chunk.toString(), 'stderr');
  });
  return kid2.stdout.on('data', function(chunk) {
    return refresh(chunk.toString());
  });
};
