// Generated by CoffeeScript 1.6.3
var colors, hound, sep;

hound = require('hound');

colors = require('colors');

sep = require('path').sep;

module.exports.watcher = function(opts) {
  var emitter, error, watchdir;
  if (!((opts.path != null) && (opts.handler != null))) {
    return;
  }
  watchdir = process.cwd() + sep + opts.path;
  try {
    emitter = hound.watch(watchdir);
    emitter.on('change', opts.handler.change);
    return console.log('ipso:' + (" watching directory: ." + sep + opts.path).grey);
  } catch (_error) {
    error = _error;
    if (error.errno === 34) {
      return console.log('ipso:' + (" expected directory: ." + sep + opts.path).red);
    } else {
      return console.log('ipso:' + (" exception " + error).red);
    }
  }
};
